image: node:11.6

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build:prod
  - mkdir public
  - cp -r build public
  - cp index.html public

  artifacts:
    paths:
    - public
  only:
    - master